'use client';
import { useState } from 'react';
import { Download, ArrowLeft, Undo2, UserPlus } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Table, TableBody, TableHead, TableHeader, TableRow, TableCell } from '@/components/ui/table';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import { rules, categories, calculateScores, bottomFive, signed, parseRoster, validDate, type Classroom, type Rule, type Entry } from '@/lib/classroom';
import { downloadWorkbook } from '@/lib/export-workbook';

type Props={data:Classroom;dialog:string|null;setDialog:(value:string|null)=>void;week:{start:string;end:string};user:{name:string;email:string}|null;busy:boolean;mutate:(input:Record<string,unknown>)=>Promise<Classroom>;onRule:(rule:Rule)=>void;editingRule?:Rule;onVoid:(input:{entryId?:string;batchId?:string;reason:string})=>Promise<void>};
export function Choice({value,onChange,label,options}:{value:string;onChange:(v:string)=>void;label:string;options:{value:string;label:string}[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="choice" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
export default function ClassroomDialogs({data,dialog,setDialog,week,user,busy,mutate,onRule,editingRule,onVoid}:Props){
 const [tab,setTab]=useState('class'),[rosterText,setRosterText]=useState(''),[className,setClassName]=useState(data.demo?'我的班级':data.name),[operator,setOperator]=useState(data.demo?user?.name||'':data.operator||'');
 const [email,setEmail]=useState(''),[memberName,setMemberName]=useState(''),[memberPassword,setMemberPassword]=useState('');
 const [start,setStart]=useState(week.start),[end,setEnd]=useState(week.end),[scope,setScope]=useState('all'),[details,setDetails]=useState(true),[exporting,setExporting]=useState(false);
 const [range,setRange]=useState('week'),[query,setQuery]=useState(''),[category,setCategory]=useState('全部'),[ruleTab,setRuleTab]=useState(editingRule?'custom':'common');
 const [customTitle,setCustomTitle]=useState(editingRule?.title||''),[customCategory,setCustomCategory]=useState(editingRule?.category||'其他'),[customPoints,setCustomPoints]=useState(editingRule?String(editingRule.points):'');
 const [voidEntry,setVoidEntry]=useState<Entry|null>(null),[voidReason,setVoidReason]=useState('登记有误'),[voidBusy,setVoidBusy]=useState(false),[rowLimit,setRowLimit]=useState(60);
 const isStudent=dialog?.startsWith('student:');const studentId=isStudent?dialog!.slice(8):null;const student=data.students.find(s=>s.id===studentId);
 const scores=calculateScores(data.students,data.entries,range==='week'?week.start:undefined,range==='week'?week.end:undefined);
 const displayedScores=(scope==='bottom'?bottomFive(scores):scope==='top'?scores.slice(0,10):scores).filter(s=>!query||s.name.includes(query)||s.number.includes(query));
 const filteredEntries=data.entries.filter(e=>(!studentId||e.studentId===studentId)&&e.date>=start&&e.date<=end&&(!query||e.title.includes(query)||data.students.find(s=>s.id===e.studentId)?.name.includes(query))).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));
 const title=dialog==='rules'?(editingRule?'修改待提交事项':'班级公约'):dialog==='settings'?(data.demo?'创建我的班级':'班级设置'):dialog==='export'?'导出积分报表':dialog==='records'?'加减分记录':isStudent?`${student?.name||'学生'}的积分记录`:dialog==='ranking'?'全班排行榜':'全班积分';
 async function submit(input:Record<string,unknown>,success:string,close=false){try{await mutate(input);toast.success(success);if(close)setDialog(null);return true}catch(e){toast.error(e instanceof Error?e.message:'保存失败，请重试。');return false}}
 async function create(){try{const students=parseRoster(rosterText);if(!className.trim()||!operator.trim())throw new Error('请填写班级名称和记录员称呼。');await submit({action:'create',name:className.trim(),operator:operator.trim(),students},'班级已创建，每位同学从 0 分开始。',true)}catch(e){toast.error((e as Error).message)}}
 async function addStudents(){try{if(await submit({action:'addStudents',students:parseRoster(rosterText)},'新同学已加入，初始积分为 0。'))setRosterText('')}catch(e){toast.error((e as Error).message)}}
 async function exportReport(){if(!validDate(start)||!validDate(end)||start>end){toast.error('请选择有效日期，开始日期不能晚于结束日期。');return}setExporting(true);try{const result=await downloadWorkbook(data,{start,end,scope:scope as 'all'|'top'|'bottom',details});toast.success(`已导出 ${result.studentCount} 位同学的 Excel 报表。`)}catch{toast.error('报表生成失败，请重试。')}finally{setExporting(false)}}
 const dateFilters=<div className="date-filters"><label>开始日期<Input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>结束日期<Input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div>;
 const rosterForm=<div className="form-section"><label htmlFor="roster-input">学生名单</label><Textarea id="roster-input" className="roster-input" rows={7} value={rosterText} onChange={e=>setRosterText(e.target.value)} placeholder={'01,张同学,第1组\n02,李同学,第1组\n03,王同学,第2组'}/><p className="help-text">每行一人：学号、姓名、小组。可从 Excel 复制三列粘贴；只填姓名时自动生成学号。</p><p className="help-text">已填 {rosterText.trim()?rosterText.trim().split(/\n/).filter(s=>s.trim()).length:0} 人 · 同名同学用学号区分</p></div>;
 const recordTable=<><Table><TableHeader><TableRow><TableHead>学生</TableHead><TableHead>事项 / 发生日期</TableHead><TableHead>分值</TableHead><TableHead>记录员</TableHead><TableHead>状态</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{filteredEntries.slice(0,rowLimit).map(e=><TableRow key={e.id} className={e.voidedAt?'voided-row':''}><TableCell>{data.students.find(s=>s.id===e.studentId)?.name}</TableCell><TableCell><span className="record-title">{e.title}</span><small className="block-meta">{e.date} · {e.category}</small><small className="block-meta">{signed(e.unitPoints??e.points)} 分 × {e.quantity??1} 次</small></TableCell><TableCell className={e.points>0?'positive':'negative'}>{signed(e.points)}</TableCell><TableCell>{e.operator}</TableCell><TableCell><span className={e.voidedAt?'status-void':'status-active'}>{e.voidedAt?'已撤销':'有效'}</span>{e.voidedAt&&<small className="block-meta">{e.voidReason}</small>}</TableCell><TableCell>{!e.voidedAt&&<button className="text-button" disabled={busy} onClick={()=>{setVoidReason('登记有误');setVoidEntry(e)}}><Undo2 size={14}/>撤销</button>}</TableCell></TableRow>)}</TableBody></Table>{filteredEntries.length===0&&<p className="empty-message">这个日期范围内还没有记录。</p>}{filteredEntries.length>rowLimit&&<button className="button load-more" onClick={()=>setRowLimit(n=>n+60)}>显示更多记录</button>}</>;
 return <><Dialog open={!!dialog} onOpenChange={open=>{if(!open&&!busy)setDialog(null)}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{data.demo?'演示数据，不会计入真实班级。':`${data.name} · 记录实时保存`}</DialogDescription></DialogHeader>
  {dialog==='settings'?<>{!user?<div className="signin-panel"><p>登录后创建班级，导入真实名单并保存加减分记录。</p><a className="button button-primary" href="/login" target="_top">登录班级账号</a></div>:data.demo?<><div className="form-grid"><label>班级名称<Input aria-label="班级名称" value={className} maxLength={40} onChange={e=>setClassName(e.target.value)}/></label><label>记录时显示的称呼<Input aria-label="记录员称呼" value={operator} maxLength={30} onChange={e=>setOperator(e.target.value)}/></label></div>{rosterForm}<div className="form-note">导入后的每位同学从 0 分开始；演示班级的记录不会带入。</div><button className="button button-primary" disabled={busy} onClick={create}>{busy?'正在创建…':'创建班级并导入名单'}</button></>:data.role!=='owner'?<p className="form-note">班级名册和记录员名单由老师或管理员维护。当前登录：{user.email}</p>:<Tabs value={tab} onValueChange={setTab} className="settings-tabs"><TabsList><TabsTrigger value="class">班级信息</TabsTrigger><TabsTrigger value="roster">添加同学</TabsTrigger><TabsTrigger value="members">学生记录员</TabsTrigger></TabsList><TabsContent value="class"><div className="form-grid"><label>班级名称<Input value={className} maxLength={40} onChange={e=>setClassName(e.target.value)}/></label><label>我的记录称呼<Input value={operator} maxLength={30} onChange={e=>setOperator(e.target.value)}/></label></div><p className="help-text account-line">当前账号：{user.email}</p><button className="button button-primary" disabled={busy||!className.trim()||!operator.trim()} onClick={()=>submit({action:'settings',name:className.trim(),operator:operator.trim()},'班级设置已保存。')}>保存设置</button></TabsContent><TabsContent value="roster">{rosterForm}<p className="form-note">已有 {data.students.length} 位同学。新同学使用未占用的学号，现有积分不会改变。</p><button className="button button-primary" disabled={busy||!rosterText.trim()} onClick={addStudents}><UserPlus size={16}/>添加同学</button></TabsContent><TabsContent value="members"><p className="help-text">最多设置 2 名学生记录员。下面的邮箱作为登录账号，不需要验证或收邮件。</p><div className="members-list">{data.members?.map(m=><div key={m.email}><span><strong>{m.name}</strong><small>{m.email}</small></span><span>{m.role==='owner'?'管理员':<button className="text-button" disabled={busy} onClick={()=>submit({action:'removeMember',email:m.email},'已移除该记录员的登记权限。')}>移除</button>}</span></div>)}</div><div className="form-grid"><label>登录账号（邮箱）<Input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>记录员称呼<Input value={memberName} maxLength={30} onChange={e=>setMemberName(e.target.value)}/></label></div><label className="form-section">登录密码<Input type="password" autoComplete="new-password" placeholder="新账号至少 10 位；已有账号留空保留密码" value={memberPassword} maxLength={128} onChange={e=>setMemberPassword(e.target.value)}/></label><button className="button button-primary" disabled={busy||!email||!memberName.trim()} onClick={async()=>{if(await submit({action:'member',email,name:memberName.trim(),...(memberPassword?{password:memberPassword}:{})},'记录员已保存。')){setEmail('');setMemberName('');setMemberPassword('')}}}>保存记录员账号</button></TabsContent></Tabs>}</>
  :dialog==='rules'?<Tabs value={ruleTab} onValueChange={setRuleTab} className="settings-tabs"><TabsList><TabsTrigger value="common">公约事项</TabsTrigger><TabsTrigger value="custom">手动登记事项</TabsTrigger></TabsList><TabsContent value="common"><Choice label="公约类别" value={category} onChange={setCategory} options={['全部',...categories].map(s=>({value:s,label:s}))}/><div className="dialog-rule-grid">{rules.filter(r=>category==='全部'||r.category===category).map(r=><button key={r.id} className="rule" onClick={()=>{onRule(r)}}><span><small className="block-meta">{r.category}</small>{r.title}</span><strong className={r.points>0?'positive':'negative'}>{signed(r.points)}</strong></button>)}</div>{!rules.some(r=>category==='全部'||r.category===category)&&<p className="empty-message">该类事项需要确认分值后手动登记。</p>}<p className="form-note">迟到递增、严重违纪、卫生奖励叠加等分值，请先按老师确认的规则，使用“手动登记事项”。</p></TabsContent><TabsContent value="custom"><div className="form-section"><label>事项名称<Input aria-label="自定义事项名称" placeholder="例如：本周第二次迟到" value={customTitle} maxLength={80} onChange={e=>setCustomTitle(e.target.value)}/></label></div><div className="form-grid"><label>类别<Choice label="自定义事项类别" value={customCategory} onChange={setCustomCategory} options={categories.map(s=>({value:s,label:s}))}/></label><label>单次加减分值<Input aria-label="自定义分值" type="number" step="1" min="-100" max="100" placeholder="加分填 1，扣分填 -1" value={customPoints} onChange={e=>setCustomPoints(e.target.value)}/></label></div><p className="help-text">请填写老师确认的整数分值，不能为 0。</p><button className="button button-primary" onClick={()=>{const points=Number(customPoints);if(!customTitle.trim()||!Number.isInteger(points)||!points||Math.abs(points)>100){toast.error('请填写事项名称和有效整数分值。');return}onRule({id:'custom',title:customTitle.trim(),category:customCategory,points})}}>{editingRule?'保存修改':'添加到待提交事项'}</button></TabsContent></Tabs>
  :dialog==='export'?<>{dateFilters}<div className="form-section"><label>导出范围</label><Choice label="导出范围" value={scope} onChange={setScope} options={[{value:'all',label:'全班同学'},{value:'top',label:'前 10 位'},{value:'bottom',label:'后 5 名（含边界同分）'}]}/></div><label className="checkbox-label"><Checkbox checked={details} onCheckedChange={value=>setDetails(value===true)}/>同时导出逐笔加减分明细</label><div className="form-note">Excel 内含期初积分、本期加分、扣分、净积分与期末积分。已撤销记录不会计入总分。</div><button className="button button-primary" disabled={exporting} onClick={exportReport}><Download size={17}/>{exporting?'正在生成…':'下载 Excel 报表'}</button></>
  :dialog==='records'||isStudent?<>{isStudent&&<div className="student-detail-summary"><strong>{student?.number} 号 · {student?.name}</strong><span>累计积分 <b>{signed(calculateScores(data.students,data.entries).find(s=>s.id===studentId)?.total||0)}</b></span></div>}{dateFilters}<Input aria-label="筛选积分记录" placeholder={isStudent?'搜索事项':'搜索学生姓名或事项'} value={query} onChange={e=>{setQuery(e.target.value);setRowLimit(60)}}/>{recordTable}{isStudent&&<button className="text-button" onClick={()=>setDialog('ranking')}><ArrowLeft size={15}/>返回全班排行榜</button>}</>
  :<><div className="dialog-toolbar"><Choice label="排名统计周期" value={range} onChange={setRange} options={[{value:'week',label:`本周 ${week.start.slice(5)}—${week.end.slice(5)}`},{value:'all',label:'全部累计积分'}]}/><Choice label="排行榜范围" value={scope} onChange={setScope} options={[{value:'all',label:'全部同学'},{value:'top',label:'前 10 位'},{value:'bottom',label:'后 5 名（含并列）'}]}/></div><Input aria-label="筛选全班积分" placeholder="搜索姓名或学号" value={query} onChange={e=>setQuery(e.target.value)}/><Table><TableHeader><TableRow><TableHead>名次</TableHead><TableHead>学号</TableHead><TableHead>姓名</TableHead><TableHead>加分</TableHead><TableHead>扣分</TableHead><TableHead>净积分</TableHead></TableRow></TableHeader><TableBody>{displayedScores.map(s=><TableRow key={s.id}><TableCell>{s.rank}{s.tied&&<small className="tie-label">并列</small>}</TableCell><TableCell>{s.number}</TableCell><TableCell><button className="text-button" onClick={()=>setDialog('student:'+s.id)}>{s.name}</button></TableCell><TableCell className="positive">+{s.plus}</TableCell><TableCell className="negative">−{s.minus}</TableCell><TableCell className={s.total<0?'negative':'positive'}>{signed(s.total)}</TableCell></TableRow>)}</TableBody></Table>{displayedScores.length===0&&<p className="empty-message">没有符合筛选条件的同学。</p>}<p className="help-text">从 0 分开始计算，未发生加减分的同学也参与排名。同分共享名次。</p></>}
 </DialogContent></Dialog><AlertDialog open={!!voidEntry} onOpenChange={open=>{if(!open&&!voidBusy)setVoidEntry(null)}}><AlertDialogContent className="confirm-dialog"><AlertDialogHeader><AlertDialogTitle>撤销这笔记录？</AlertDialogTitle><AlertDialogDescription>{voidEntry?`${data.students.find(s=>s.id===voidEntry.studentId)?.name} · ${voidEntry.title} · ${signed(voidEntry.points)} 分。撤销后会重新计算积分和排名，原记录保留。`:''}</AlertDialogDescription></AlertDialogHeader><Input aria-label="撤销原因" placeholder="填写撤销原因" value={voidReason} maxLength={120} onChange={e=>setVoidReason(e.target.value)}/><AlertDialogFooter><AlertDialogCancel disabled={voidBusy}>取消</AlertDialogCancel><AlertDialogAction disabled={voidBusy||!voidReason.trim()} onClick={async e=>{e.preventDefault();if(!voidEntry)return;setVoidBusy(true);try{await onVoid({entryId:voidEntry.id,reason:voidReason.trim()});setVoidEntry(null)}catch(error){toast.error(error instanceof Error?error.message:'撤销失败，请重试。')}finally{setVoidBusy(false)}}}>{voidBusy?'正在撤销…':'确认撤销'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
